// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzXRcuhUkC6Us_b_XtH4ZQUnGdrK1U7oQ',
    appId: '1:548397016677:web:ff35d807da11bca6fc088c',
    messagingSenderId: '548397016677',
    projectId: 'bookphoria-78fc0',
    authDomain: 'bookphoria-78fc0.firebaseapp.com',
    storageBucket: 'bookphoria-78fc0.appspot.com',
    measurementId: 'G-BHPD1PNKFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBGg6X05_D97Iglf7CRlFWzXAScEjH_aI',
    appId: '1:548397016677:android:2074783f5bd23e41fc088c',
    messagingSenderId: '548397016677',
    projectId: 'bookphoria-78fc0',
    storageBucket: 'bookphoria-78fc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlY5CtPq6JSnRDbAsqwYSXSAcUoDk7d6I',
    appId: '1:548397016677:ios:07c6622746c0950afc088c',
    messagingSenderId: '548397016677',
    projectId: 'bookphoria-78fc0',
    storageBucket: 'bookphoria-78fc0.appspot.com',
    iosBundleId: 'com.example.proyekAkhirSemester',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlY5CtPq6JSnRDbAsqwYSXSAcUoDk7d6I',
    appId: '1:548397016677:ios:240b12cf09a77862fc088c',
    messagingSenderId: '548397016677',
    projectId: 'bookphoria-78fc0',
    storageBucket: 'bookphoria-78fc0.appspot.com',
    iosBundleId: 'com.example.proyekAkhirSemester.RunnerTests',
  );
}
